### ISSUE TITLE
“最笑你个信勃勃” 是什么？

### ISSUE THREAD

**Issue by skys215** [le0zh0u/startup-checklist#1]
见代码：
https://github.com/le0zh0u/startup-checklist/blob/4d0e668f895372907b1a17305c52093bc74beaac/src/components/HelloWorld.vue#L216

**Comment by le0zh0u** [comment]
感谢反馈，翻译时没注意打字的结果导致。这个问题是「在25年的时间范围内，你的公司最有志向且可实现的里程碑是什么？」。已经修正并且发布。

**Comment by skys215** [comment]
好的，感谢！
